sudo: required

services:
  - docker

env:
  global:
    - secure: b27FWRcUWnOCN1R6AFTqse+HxKFadlCnfPd8NBvzd8NyTWkyVkiu2Q0zaC3BgVtEP3F9h1Qrjhaf/hRrkfxqANaOv5cfy4bwUUYO3O0FdGSNre1vXW757qL1Yy9QFH/C1oHmD50pA7h37RNrO5bz9U08fibyKKEWND/Iu9hJapcKBR6qqTJ85zs5t5m1vpGT1VrqCLfHFjaqv+xILH4GG0VElSKl1aDL1bP/AZdCAAgUOs2S/xsqgdJygcHLlcifH0BSHgxf7AySH/WJURTkJ9Yns0woXZ3IL51B/KFu/B7l3wadvqrc8LgEf5PHPpbE77JSXm+QvKQtGCrHjjMZ+7NaQpwIaHOBcl0snWVRjhaHQmGiUxbYbuhnrxT2iKBfCx9Z+c0HtZTVplTQdwIBh7sVQIwkt9uZagfvv42OK5WrsD8+lqpCCJDMc5tcTaLzgPJrOQqI4hAekw5s2UdwNjQc+5zO/dWAyIRO6JCjJghwLnmBCEabT3ZD349WRvqVB/O67akGYxUThR2XzQ6mD5k45xVcgWtoE81sDQOwGKKiMzVcmw8W4FQTqhBKYydVLQQ/16pvvsRqKLS3QH7nL0CYqCLWyd0UA+SOOPb5RMtm3XdavMS99b03W590KWnMm8x1LUmMfK4DFeWmVWa9Gj+zS/ELAFdgqESmZOOip84=
    - secure: IbHcSQpyA6hG3gMiZs9tQe+na8hMCCIpU83xAy3IXqRDG+n9uB/1zQKKLK5WjQC2xGhRZOL9O3oe7ukfB/WGCqh/U3na6UPn8oITVJgOcYOOpoUgmRyj3w3U4E9T6zKZBG0K1n7MftVqeSPB+iSPXSia51TQ6kefLAhtRX00TpIZDrCHPsUNFV71fHibZS/TJVUGOfLwr0paU/gNAnHflVGbWraNPwzWM69AodbvY9etZSTD5O5IW41PeiSaPaLf9VOI3TWbJzLdAhZvGV9RRFGjcaFQCRh+LZgv+fw+S+aLb+kX9qLd1DHDAdppsqoMRpiomvbMfKcnzwvW3cLvaqbmx5Q3kN2dcZe7tTZxvODtr/gFieSl/YPjj3ihhHBqYNYb33bRkRiBaQIaZyOaScaS3k/DiGBfNcbjhbtglNThP3lZU6NAUApuON9Cp1izgfpERy+XJYFxs6XTl4QEoakX7fOfgcOwIEDiVFoaLtryu/29aFKS9/zsmJeWoOi4kkWhmBEfR+B3LkOjKsiIOS9T3dKcC6FJYfma/tRlKMwqCMNqLYzm1gK9deAVDsS7q3mEqKc4zFQqEdx0IL8d3+YrR49HlC5ODxHxQCE0TbxCFKCpb7xbeIkFvMDef3mEBzvKuBRhC/cV7IXZiXmkPKzKk9vhkcjcXYdaGUhyxYg=
  matrix:
    - LATEST=1 PACKER_VERSION=1.4.3 AWSCLI_VERSION=1.16.245 INSPEC_VERSION=4.16.0 ANSIBLE_VERSION=2.8.5
    - LATEST=0 PACKER_VERSION=1.3.5 AWSCLI_VERSION=1.16.125 INSPEC_VERSION=3.7.1 ANSIBLE_VERSION=2.7.9
    - LATEST=0 PACKER_VERSION=1.3.5 AWSCLI_VERSION=1.16.125 INSPEC_VERSION=3.7.1 ANSIBLE_VERSION=2.6.3
    - LATEST=0 PACKER_VERSION=1.2.4 AWSCLI_VERSION=1.15.42 INSPEC_VERSION=2.2.16 ANSIBLE_VERSION=2.5.5
    - LATEST=0 PACKER_VERSION=1.2.4 AWSCLI_VERSION=1.15.42 INSPEC_VERSION=2.1.84 ANSIBLE_VERSION=2.5.5

script:
  - bash dockerBuild.sh

# Do some informational output
before_deploy:
  - docker images

deploy:
  provider: script
  script: bash dockerPush.sh
  on:
    all_branches: true

# Do some informational output
after_script:
  - docker images
