sudo: required

services:
  - docker

env:
  global:
    - secure: gysEB/+mqdJVc5rDhweVYBRNRZZU1yxxkMqnubyaKDfL+F38xkR/bFwg6IirjswnCSYh1jWKVTaC8QnOYLGAx1/RJu+MgbJkCxsbsZuMMgGc/oq7RQD2PwhxBjdIF3KwRfG74qzCROgQ5+WyDe457BdJzOxsq8+3kRLsxflyzEGTRzTWp81Oi4p4RJL9p560LRkYOi7olMVrBOvGqmhyduVnk56m73igv4/DBn4JyamTn2xwVGVKuHiphXBafhvp3ctGA10Zw3lhJLOnUJDF1n11TCmMfagSzpGhtOIBlkpL7LCtn9Oro3UZLeqNTBm24UN1qGL1W4xh7lMxZRnOXTce1E+S7qJxkQRwqPpQmDq8cbSs7n5GCBh9/AvzWqzyNnYaZXbd4uI1Je799LjOJyIDCB/eYRAf5uXjdwKoiCqY6j6X9LnXvVKusN8ipBqO/bcAQuSqcxndWj2w8xCHG0NiJ63RNEUJ8I/nyFe0nEPO7rU/1jm5PglWaGglMKEDIdnZ/U5OoT79BVlLr4/R8wO7G7kYb71ttUDO5McavEeCNfxdMcBpTn65BPZBndC+GrvAo0J6ixpfbpIcEslySNYUJXy3e6fEwCy4ciqXf9Q0uNHoohs+8JGKOb1TdKkjQKUkBY3gwR1Et+t8C2Ialn45gMzQGPVLOB8Lfvg+iyI=
    - secure: k1we19Kj/IJ5lJuzKp2kjN4PXktGAXwKjidPF7h3KvVK5ElU33hmqhhsE7KEJu0a7joBD61c2MLmKg/Eo5IvNbYTMoGnX9C9oHOAigM8P7K4+IXMWbzexrNkEqzRBTUv4cLoL5cTCS3aHAyck/mbg6B59KxsSS6NL6xXav+HwWNxT7hPwOuUE1A+3EdJet2BvY4vjIFEs60n7zj1dVTlBGisNBGyEbZWk1zO1SgKwln1ysJL+99cafE4VPb5PHvWTH/vuAoMsUTwt2Xp083qbcoSSM7ozarTlv4C/XMZ6SbBauCGQtmKswXqq6nMN4oDiswA80pQoNyVKyHuvMRpP29Cu7GMefvZ0GGQGAxwxLWU9+RSQFh5dkgJ98s9l1sG23PA3E2GcxHc7WjT2u9C18FEmwW8dUGlizdgF8WiMvc+mJkb/+VuHzEm5mrm335uGDA5hY592VDMZYeMLmG5VMxkv3OqM1ureJDoq6vX5RuQmLVbOg+m2pOcsCr+rp64qwm4R1MxtUBJB+3AeUaXoh/EEWo1cnog0Frak1/iFshtV3SDiVElJLFupKbl5q6n4/Et1Vb5hmwl3wpfk8xgTMb5cLp557gykI/jVYnUMNerx0LQzqf6tvkJgZ6wGQERWxr2zKtUSF5xEAZ/UylTy4GP9zjnqbdtjZYQldpMTUk=
  matrix:
  - LATEST=1 PACKER_VERSION=1.3.5 AWSCLI_VERSION=1.16.125 INSPEC_VERSION=3.7.1 ANSIBLE_VERSION=2.7.9
  - LATEST=0 PACKER_VERSION=1.3.5 AWSCLI_VERSION=1.16.125 INSPEC_VERSION=3.7.1 ANSIBLE_VERSION=2.6.3
  - LATEST=0 PACKER_VERSION=1.2.4 AWSCLI_VERSION=1.15.42 INSPEC_VERSION=2.2.16 ANSIBLE_VERSION=2.5.5
  - LATEST=0 PACKER_VERSION=1.2.4 AWSCLI_VERSION=1.15.42 INSPEC_VERSION=2.1.84 ANSIBLE_VERSION=2.5.5

script:
  - bash dockerBuild.sh

# Do some informational output
before_deploy:
  - docker images

deploy:
  provider: script
  script: bash dockerPush.sh
  on:
    branch: master

# Do some informational output
after_script:
  - docker images
